name: Deploy

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build -x test
    
    - name: Build Docker image
      run: |
        docker build -t community-board:${{ github.sha }} .
        docker tag community-board:${{ github.sha }} community-board:latest
    
    # AWS EC2 배포 예시 (필요시 활성화)
    # - name: Deploy to EC2
    #   env:
    #     EC2_HOST: ${{ secrets.EC2_HOST }}
    #     EC2_USER: ${{ secrets.EC2_USER }}
    #     EC2_KEY: ${{ secrets.EC2_KEY }}
    #   run: |
    #     echo "$EC2_KEY" > key.pem
    #     chmod 600 key.pem
    #     scp -i key.pem -o StrictHostKeyChecking=no build/libs/*.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/
    #     ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "sudo systemctl restart community-board"
    #     rm key.pem
    
    # Docker Hub 푸시 예시 (필요시 활성화)
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    
    # - name: Push to Docker Hub
    #   run: |
    #     docker tag community-board:latest ${{ secrets.DOCKER_USERNAME }}/community-board:latest
    #     docker push ${{ secrets.DOCKER_USERNAME }}/community-board:latest